version: '3'

services:
  migration:
    image: "wertbon1789/wikijs-migration:0.1.0"
    container_name: wikijs-migration
    build:
      context: ./build
      dockerfile: ./Dockerfile
    environment:
      - WIKIJS_HOST=${WIKIJS_HOST}
      - WIKIJS_TOKEN=${WIKIJS_TOKEN}
      - MEDIAWIKI_SSH_HOST=${MEDIAWIKI_SSH_HOST}
      - MEDIAWIKI_SSH_PORT=${MEDIAWIKI_SSH_PORT}
      - MEDIAWIKI_SSH_USER=${MEDIAWIKI_SSH_USER}
      - MEDIAWIKI_SSH_PASSWD=${MEDIAWIKI_SSH_PASSWD}
