version: '3'

services:
  migration:
    image: "wertbon1789/wikijs-migration:0.1.7"
    container_name: wikijs-migration
    build:
      context: ./build
      dockerfile: ./Dockerfile
    environment:
      - WIKIJS_HOST=${WIKIJS_HOST}
      - WIKIJS_TOKEN=${WIKIJS_TOKEN}
      - MEDIAWIKI_SSH_HOST=${MEDIAWIKI_SSH_HOST}
      - MEDIAWIKI_SSH_PORT=${MEDIAWIKI_SSH_PORT}
      - MEDIAWIKI_SSH_USER=${MEDIAWIKI_SSH_USER}
      - MEDIAWIKI_SSH_PASSWD=${MEDIAWIKI_SSH_PASSWD}
      - MEDIAWIKI_ASSETS=${MEDIAWIKI_ASSETS}
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_PORT=${PSQL_PORT}
      - IMPORT_LDAP=${IMPORT_LDAP}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_ADMIN_DN=${LDAP_ADMIN_DN}
      - LDAP_ADMIN_PASSWD=${LDAP_ADMIN_PASSWD}
      - LDAP_USERS_DN=${LDAP_USERS_DN}
      - LDAP_FILTER=${LDAP_FILTER}
      - USER_TIMEZONE=${USER_TIMEZONE}
    volumes:
      - wiki_migration_data:/data:rw
      - "./username_mapping.json:/username_mapping.json:ro"

volumes:
  wiki_migration_data:
